version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    command: bash -c "docker-php-ext-install mysqli && \
                      docker-php-ext-enable mysqli && \
                      apache2-foreground"

  db:
    image: mysql:8.1.0 
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: link_shortner_db
    ports: 
        - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db